gpu_id: 1
# Dataset config
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
#RATING_FIELD: label
#LABEL_FIELD: label
RATING_FIELD: rating
LABEL_FIELD: rating
load_col:
#    inter: [user_id, item_id, label]
    inter: [user_id, item_id, rating]
    item: [item_id,movie_title,release_year,class]
    user: [user_id,age,gender,occupation,zip_code]
user_inter_num_interval: [13,100]

# Training and evaluation config
#seed: 1128
epochs: 200
train_batch_size: 32
#valid_metric: ndcg@5
valid_metric: ndcg@7

# Evaluate config
eval_args:
    group_by: task
    order: RO
    split: {'RS': [0.8,0.1,0.1]}
    mode : labeled

# Meta learning config
meta_args:
    support_num: none
    query_num: 10

# MeLU Parameters
embedding_size: 32
mlp_hidden_size: [64,64]
grad_meta_args:
    local_lr: 5e-5
    lr: 5e-4

normalize_all: True

# Metrics
metrics: ['mae','rmse', 'ndcg']
metric_decimal_place: 4
topk: [1, 3, 5, 7]
